window.fontList = [
    'Arial',
    'Arial Black',
    'Arial Narrow',
    'Arial Rounded MT Bold',
    'Baskerville',
    'Bodoni MT',
    'Book Antiqua',
    'Bookman Old Style',
    'Calibri',
    'Cambria',
    'Candara',
    'Comic Sans MS',
    'Courier New',
    'Georgia',
    'Gill Sans',
    'Helvetica',
    'Impact',
    'Lucida Console',
    'Lucida Sans Unicode',
    'Microsoft Sans Serif',
    'Palatino Linotype',
    'Segoe UI',
    'Tahoma',
    'Times New Roman',
    'Trebuchet MS',
    'Verdana',
    'Webdings',
    'Wingdings',
    'Georgia',
    'Garamond',
    'Helvetica Neue',
    'Frank Ruhl Libre',
    'Roboto',
    'Open Sans',
    'Lato',
    'Montserrat',
    'Raleway',
    'Poppins',
    'Oswald',
    'Droid Sans',
    'Ubuntu',
    'Fira Sans',
    'Source Sans Pro',
    'Merriweather',
    'Noto Sans',
    'Quicksand',
    'Archivo',
    'Exo 2',
    'Playfair Display',
    'PT Sans',
    'Inconsolata',
    'Overpass',
    'Noto Serif',
    'Abril Fatface',
    'Anton',
    'Bebas Neue',
    'Dancing Script',
    'Pacifico',
    'Sacramento',
    'Raleway Dots',
    'Satisfy',
    'Lobster',
    'Abril Fatface',
    'Alegreya',
    'Montserrat Alternates',
    'Muli',
    'Titillium Web',
    'Roboto Slab',
    'Zilla Slab',
    'Avenir',
    'Century Gothic',
    'Frank Ruhl Libre',
    'Karla',
    'Neuton',
    'Pangolin',
    'Righteous',
    'Vollkorn',
    'Zilla Slab',
    'Chivo',
    'Exo',
    'Noto Serif',
    'Cabin',
    'Spectral',
    'Julius Sans One',
    'Tisa',
    'Old Standard TT',
    'Fjalla One',
    'Amatic SC',
    // Add more fonts as necessary
];
